#!/bin/bash
# hooks/build
# https://docs.docker.com/docker-cloud/builds/advanced/

# $IMAGE_NAME var is injected into the build so the tag is correct.
echo "[***] Build hook running"
echo "[***] - DokerRepo : $DOCKER_REPO"
echo "[***] - Version   : $SOURCE_BRANCH"
echo "[***] - ImageName : $IMAGE_NAME"


if [ "$SOURCE_BRANCH" == "master" ]; then
    docker build \
		-t $IMAGE_NAME .
else
	docker build \
		--build-arg OMBI_VER=$SOURCE_BRANCH \
		-t $IMAGE_NAME .
fi
